package constants

//ISSUERPUB issuer public
var ISSUERPUB = "GDUQM4RJ37OHGZOSTTJRYKEVUSPQFDNQVCKZBVRXOE4YRH3YQTNOLA63"

//ISSUERSEC issuer secret
var ISSUERSEC = "SDNNP3BPEW2RBBUZI7OOILSZM5Z3WUA4R4EGKU3JL7EIYKWIQIGJF4W4"
