package constants

//ISSUERPUB issuer public
var ISSUERPUB = "GD5VAU3K6RQE5SUPNJADXMMYNXYQREO5YW334T23N43IHNPJT2DAPPME"

//ISSUERSEC issuer secret
var ISSUERSEC = "SAN4OGSRPIT72GEQHUZ3U4XUMQNEDZMJ3CIQCJNDPRGPEVNW62I2HM5W"



//JIGXUISSUERPUB JIGXU issuer public
var JIGXUISSUERPUB = "GD5VAU3K6RQE5SUPNJADXMMYNXYQREO5YW334T23N43IHNPJT2DAPPME"

//JIGXUISSUERSEC JIGXU issuer secret
var JIGXUISSUERSEC = "SAN4OGSRPIT72GEQHUZ3U4XUMQNEDZMJ3CIQCJNDPRGPEVNW62I2HM5W"





//JIGXKISSUERPUB JIGXK issuer public
var JIGXKISSUERPUB = "GD5VAU3K6RQE5SUPNJADXMMYNXYQREO5YW334T23N43IHNPJT2DAPPME"

//JIGXKISSUERSEC JIGXK issuer secret
var JIGXKISSUERSEC = "SAN4OGSRPIT72GEQHUZ3U4XUMQNEDZMJ3CIQCJNDPRGPEVNW62I2HM5W"